---
- hosts: localhost
  gather_facts: False
  sudo: False
  tasks:
    
    - name: check out required roles
      delegate_to: localhost
      connection: local
      git:
        repo: "{{ openstack_repository_prefix }}ansible-role-{{ item }}.git"
        dest: roles/{{ item }}
        update: yes
      with_items:
        - chrony
        - docker
